### PR TITLE
Add MS mails to recipient list

### PR DESCRIPTION
**Pull request by hanefi**
Only @byucesoy and @metdos used to receive valgrind mails. I added your MS emails, and added mine at the end.

If the mails successfully hit our MS inboxes, we will then remove our Citus mails

### CODE REVIEW

**Comment by byucesoy** [comment]
I got notification for this PR and realized this and previous PRs opened against wrong repo. This repo is obsoleted and it is not used anymore. Valgrind automation code lives [here](https://github.com/citusdata/tools/tree/develop/valgrind).

Please let me know after you apply your changes to the other repo so that I can;
- Remove this repo to eliminate further confusion
- Deploy latest changes to valgrind automation machine.

**Comment by hanefi** [comment]
Thanks @byucesoy for pointing this out.

I created a new PR in the correct repo https://github.com/citusdata/tools/pull/44

Also changes in my previous PR #4 are already there in the [tools repo](https://github.com/citusdata/tools/tree/develop/valgrind) so we do not need to take any more action there.

**Comment by byucesoy** [comment]
@hanefi  is it OK to remove this repo? Do we have anything here we want to keep?

**Comment by hanefi** [comment]
We discussed this offline. It is ok with me. Let's remove this repo to avoid further confusion

**Comment by metdos** [comment]
I'm deleting this repo.

**Pull request merged**
